-- Deploy schema changes from freenetis (test) -> freenetis-pvfree (prod)
-- Generated by ChatGPT (based on provided SQL dumps)
START TRANSACTION;

-- 1) invoices: add pdf_filename
ALTER TABLE `invoices`
  ADD COLUMN `pdf_filename` varchar(64) DEFAULT NULL;

-- 2) bank_accounts: add payment_purpose
ALTER TABLE `bank_accounts`
  ADD COLUMN `payment_purpose` tinyint(1) NOT NULL DEFAULT 0
  COMMENT '0=contribution(receipt notice), 1=services(issue invoice)';

-- 3) new table: email_queue_attachments
CREATE TABLE IF NOT EXISTS `email_queue_attachments` (
  `id` int(11) NOT NULL,
  `email_queue_id` int(11) NOT NULL,
  `path` varchar(1024) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `mime` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;

COMMIT;
